### ISSUE TITLE
Holidays are missing in the federal states of Germany

### ISSUE THREAD

**Issue by webtimo-de** [openpotato/openholidaysapi.data#11]
Hello, 
I noticed that the Christmas holidays and other holidays are missing in the federal states of Germany. I tested here, in North Rhine-Westphalia the Christmas holidays from 2024 to 2025 are missing as well as the autumn holidays. I haven't looked any further, but it would be nice if this were updated. Thank you in advance (:

![grafik](https://user-images.githubusercontent.com/43751284/215081336-780be70c-6ed0-4681-9004-6ddff6451698.png)

https://www.schulministerium.nrw/ferienordnung-fuer-nordrhein-westfalen-fuer-die-schuljahre-bis-202930

**Comment by fstueber** [comment]
Hi, thanks for feedback. Yep, somehow I missed that. Will add the data today.

**Comment by fstueber** [comment]
Done. New school holidays (until 2030) for Baden-Württemberg and North Rhine-Westphalia added. The remaining federal states will come during the next days.

**Comment by webtimo-de** [comment]
Thank you very much, could you possibly let me know here in the issue if you add the other school holidays as well? Then I can start the import again. Thank you for the quick response and for the school holidays in North Rhine-Westphalia and Baden-Württemberg (:

**Comment by fstueber** [comment]
You can watch this repository (click on "Watch" in the top right-hand corner) to be informed of any future changes.
