### ISSUE TITLE
Quality assurance missing

### ISSUE THREAD

**Issue by sv1990** [openpotato/openholidaysapi.data#12]
It is a problem that the data in this project is not really reliable. There are again several occurences where the holiday end date is before the start date or is over a year later. There are also obvious typos like `" D"` instead of `"DE"` as a language code. Most of these Bugs could be automatically detected.
 
Ideally there would be  a GittHub action running for each Commit and Push request  that performs some costistency checks.

**Comment by fstueber** [comment]
Totally agree. Data is of course entered manually. This leads to mistakes. Will do some aurtomated checking this week. Stay tuned.

**Comment by fstueber** [comment]
All known data bugs fixed. Please check.

**Comment by sv1990** [comment]
I just checked, the data looks better now. Bulgaria and Latvia have some suspiciously long school holidays but that could also be fine. I don't have the time now to doublecheck that

**Comment by fstueber** [comment]
For Latvia summer holidays are 2 months, for Bulgaria they are even longer (always end on September 14).
