### ISSUE TITLE
Austrian state specific school holidays

### ISSUE THREAD

**Issue by kapsiR** [openpotato/openholidaysapi.data#14]
There are some missing school holidays in Austria that depend on the subdivision:  
https://www.bmbwf.gv.at/Themen/schule/schulpraxis/termine/feiertage.html

Would they fit in `holidays.school.csv`?

**Comment by fstueber** [comment]
Hi, thanks for your feedback. Yes, exactly, `holidays.school.csv` is the right file.

**Comment by fstueber** [comment]
All Souls' Day and feast days of the national patron saints added now as additional school holidays for Austria. Please check.

**Comment by kapsiR** [comment]
Thanks, indeed! Resolved with https://github.com/openpotato/openholidaysapi.data/commit/8b0d22606cd4046a1b3a1d92ea0e5a4c13e998bf
