### ISSUE TITLE
How are Ids built?

### ISSUE THREAD

**Issue by Connum** [openpotato/openholidaysapi.data#19]
I might be interested in adding data for more European countries, like Italy which is missing right now. How are the unique ids being generated? Is this done by scripts or should one generate them manually and check that they are unique? That seems a bit like a hassle...

**Comment by fstueber** [comment]
That would be great. Please ask if you have more questions or need help. Concerning id generation: Those ids are GUIDs, which can be easily generated by online tools like [Free Online GUID Generator](https://guidgenerator.com/).

**Comment by 48design** [comment]
It's very unusual that there would be a collision, but is there any mechanism in place yet to make sure of that?

**Comment by fstueber** [comment]
IF there was a collision, this would immediately lead to an error when importing the data into the backend database.
