### ISSUE TITLE
Adding holidays for Italy

### ISSUE THREAD

**Issue by fstueber** [openpotato/openholidaysapi.data#25]
Initial data provided by @48design:
https://github.com/openpotato/openholidaysapi.data/tree/feature/it/src/it

**Comment by fstueber** [comment]
Questions to @48design:
- Do we have any sources for the regional patronal festivals?
- I cannot find sources for province based floating holidays (school holidays). Do I miss smething?

**Comment by 48design** [comment]
The province based floating holidays can be found in the rightmost column of the official source, the regional patronal festivals I cross-checked with different sources like other holiday calendars, announcements and Wikipedia. I didn't find legal publications for all the provinces, they might not be available online at all. It's a bit of a mess with how some countries like Italy and Spain organize their holidays and how municipalities are allowed to add their own.

**Comment by fstueber** [comment]
> The province based floating holidays can be found in the rightmost column of the official source, the regional patronal festivals I cross-checked with different sources like other holiday calendars, announcements and Wikipedia. I didn't find legal publications for all the provinces, they might not be available online at all. It's a bit of a mess with how some countries like Italy and Spain organize their holidays and how municipalities are allowed to add their own.

OK, got it. Was wondering about the region Trentino-Alto Adige, which is divided into Trentino (Autonomous Province of Trento) and South Tyrol (Autonomous Province of Bolzano).

**Comment by fstueber** [comment]
I have refactored data for Italy. See 74e6f423fdac74b8d0cccfbc141bdf94c5019eb3. 

Changes:

- Added missing school holidays for 2020
- Added source for 2019/2020 school holidays to README
- Changed codes (and short names) of subdivisions to the pattern that is used for all other countries
- Modelled LO holidays for Ambrosian rite and Roman rite with comments in holidays.school.csv (it's my approach, of course discussible)

**Comment by fstueber** [comment]
More changes to holidays.public.csv. See 522a69936919b78d6bb69fb3564566bf3d5c017c:

+ Added patronal festival for Cagliari (St. Januarius) 
+ Some changes to translations for patronal festivals 
+ Bug fixes

**Comment by fstueber** [comment]
Data merged and published. @48design: Thank you very much for your contribution. Please have a look at [README](https://github.com/openpotato/openholidaysapi.data#readme), I mentioned you there.
