### ISSUE TITLE
Adding holidays for Spain

### ISSUE THREAD

**Issue by fstueber** [openpotato/openholidaysapi.data#31]
Initial data provided by @TBiele:
https://github.com/openpotato/openholidaysapi.data/tree/feature/es/src/es

**Comment by TBiele** [comment]
For the branch to be merged into main the school holidays would still need to be added, right?

**Comment by fstueber** [comment]
Yes, school holidays + public holidays from 2020-2022

**Comment by sbeigel** [comment]
What's the status of Spanish holidays in the live API?

**Comment by fstueber** [comment]
School holidays + public holidays from 2020-2022 are still missing. It probably makes sense to publish the public holidays already.

**Comment by fstueber** [comment]
Finally published (public and school holiday). Please check?
