### ISSUE TITLE
Missing school holiday in 2024 for AT

### ISSUE THREAD

**Issue by xyso87** [openpotato/openholidaysapi.data#33]
Hello, 
in holidays.school.csv for AT there is a missing school holiday for 2024:
DE Herbstferien,EN Autumn Holidays;

Also it is missing here:
https://openholidaysapi.org/SchoolHolidays?countryIsoCode=AT&subdivisionCode=AT-VA&languageIsoCode=DE&validFrom=2024-01-01&validTo=2024-12-31

**Comment by fstueber** [comment]
Hello, the school holidays for 2024/2025 have not yet been officially announced. Source: https://www.bmbwf.gv.at/Themen/schule/schulpraxis/termine.html. 

But I have found another official source that gives at least some dates in advance (including Autumn Holidays 2024): https://www.oesterreich.gv.at/themen/bildung_und_neue_medien/schule/3/Seite.1100113.html

Will add these dates today.

**Comment by fstueber** [comment]
OK, done. Please check!

**Comment by xyso87** [comment]
Wow, thanks for the speedy support! 👍 
You are doing a great job!
