### ISSUE TITLE
Typo in Belgian subdivision: "French ommunity"

### ISSUE THREAD

**Issue by e2jk** [openpotato/openholidaysapi.data#35]
In https://openholidaysapi.org/Subdivisions?countryIsoCode=BE

The name in English of the French-speaking community is misspelled (missing the "c" in "community":

![afbeelding](https://github.com/openpotato/openholidaysapi.data/assets/229379/228ef07b-b13c-49b1-ab09-9fd8a22b0873)

**Comment by fstueber** [comment]
True. Will fix. Thank you for your feedback!

**Comment by e2jk** [comment]
Thanks for your quick response -- I've just submitted a PR to fix it

**Comment by fstueber** [comment]
I fixed it already myself.

**Comment by fstueber** [comment]
Deployed. Please check.
