### ISSUE TITLE
Missing endOfLessons dates in italy school holidays file

### ISSUE THREAD

**Issue by batrox** [openpotato/openholidaysapi.data#37]
Hello,

The end-of-school dates are published for Italy but are missing from the https://github.com/openpotato/openholidaysapi.data/blob/main/src/it/holidays/holidays.school.csv file.

Would it be possible to add them (like Portugal: EndOfLessons)?

Thanks in advance

**Comment by fstueber** [comment]
Done. Please check.

**Comment by batrox** [comment]
Thank you for your answer Frank,
I don't see any change yet ?! https://github.com/openpotato/openholidaysapi.data/commits/main/src/it/holidays/holidays.school.csv
It's written the last commit is 5 months ago

**Comment by batrox** [comment]
Sorry did not see that endOfLessons is missing for Trentino in  https://github.com/openpotato/openholidaysapi.data/blob/develop/src/it/holidays/holidays.school.csv

2024-06-11;;EndOfLessons;IT Fine delle lezioni,EN End of lessons,DE Unterrichtsende;TR-TN;

**Comment by fstueber** [comment]
Added. Thank you!
