### ISSUE TITLE
Typo in PT holidays.school.csv

### ISSUE THREAD

**Issue by batrox** [openpotato/openholidaysapi.data#38]
In https://github.com/openpotato/openholidaysapi.data/blob/main/src/pt/holidays/holidays.school.csv 
for Ids: 
0b00013c-45fe-42a1-bd51-3f03d0d5fdd0, dfc1643d-c6cb-48e7-8ce5-01fa5ba9c11e, f85477a1-d721-4330-b122-4ca5823c462c, 80031262-1458-40bd-8284-2a2843f2cea4, 8bacf741-89a7-409b-b01a-daec18f73b35

There is an extra unencoded comma in the Portuguese comments "PT 5.º%2C 6.º%2C, 7.º%2C 8.º e 10.º anos de escolaridade"

**Comment by fstueber** [comment]
Fixed. See [develop branch](https://github.com/openpotato/openholidaysapi.data/tree/develop).
