### ISSUE TITLE
PT school holidays may be wrong

### ISSUE THREAD

**Issue by batrox** [openpotato/openholidaysapi.data#39]
I checked your sources for portugal school holidays and https://github.com/openpotato/openholidaysapi.data/blob/develop/src/pt/holidays/holidays.school.csv 
In the source file they mention vacations without weekends, shouldn't they be included?

**Comment by batrox** [comment]
This would be good for standardizing data, no ?

**Comment by fstueber** [comment]
To finalise this topic. I will stick to the original data.
