### ISSUE TITLE
DE school holidays

### ISSUE THREAD

**Issue by batrox** [openpotato/openholidaysapi.data#40]
Hi,

For subdivision DE-BY Bavaria, there is a missing floating date for each school year, could you fetch them plz ?

Examples of dates missings : 
2020-11-18, 2021-11-17, 2022-11-16, 2023-11-22, 2024-11-20, and so on till 2030

**Comment by fstueber** [comment]
Source?

**Comment by fstueber** [comment]
Ah, got it: https://www.gesetze-bayern.de/Content/Document/BayFTG-4. Yes will add. Thank you!

**Comment by fstueber** [comment]
Done! Please check.

**Comment by batrox** [comment]
👍🏼👍🏼

**Comment by batrox** [comment]
👍🏼
