### ISSUE TITLE
OpenHolidays API down?

### ISSUE THREAD

**Issue by DNC74** [openpotato/openholidaysapi.data#42]
`https://openholidaysapi.org/SchoolHolidays?countryIsoCode=DE&languageIsoCode=DE&validFrom=2024-03-15&validTo=2024-04-15&subdivisionCode=DE-BW` should result to `Osterferien`.
Since the changeover to summer time, the query returns a 'null' value.

**Comment by fstueber** [comment]
Fixed

**Comment by DNC74** [comment]
👍  thank you.  May I kindly ask: What was the issue?

**Comment by fstueber** [comment]
Import of new data was broken.
