### ISSUE TITLE
Add regional public holidays in France

### ISSUE THREAD

**Issue by pYassine** [openpotato/openholidaysapi.data#48]
In France, we have specific holidays for some regions 

Alsace-moselle (FR-57)

- [ ] 26 december
- [ ] Good Friday is the Friday before Easter Monday

Also, the overseas territories all have a particular public holiday which is the date of abolition of slavery:

- [ ] Guadeloupe May 27
- [ ] Guyana June 10
- [ ] Martinique May 22
- [ ] Mayotte April 27
- [ ] Reunion December 20
- [ ] Saint-Barthélemy October 9
- [ ] Saint Martin May 27

I saw in the repo that there were files by region for Spain in particular. Is it enough to use the same model to contribute to the repo dedicated to France?

Thanks :)

**Comment by fstueber** [comment]
Hi, thanks for feedback.

According to Wikipedia the region Alsace-moselle includes FR-57, FR-67, FR-68: https://fr.wikipedia.org/wiki/Alsace-Moselle. Should we reflect this?

About French overseas territories: They have their own ISO codes. My plan was to treat them as "countries". Or is it better to include them as subdivisions for France? What do you think?

**Comment by pYassine** [comment]
Hello ! 

Yes, Alsace-moselle includes FR-57, FR-67, FR-68. I think that you should reflect this.

French overseas territories: in my opinion, it's better to include them as subdivisions. The territories are considered French overseas departments

I can Help you with a PR
