### ISSUE TITLE
17. April 2024 Feiertag in Kroatien

### ISSUE THREAD

**Issue by gildner** [openpotato/openholidaysapi.data#51]
Hallo,

der 17. April 2024 war in Kroatien ein zusätzlicher Feiertag, weil an dem Tag Wahlen stattgefunden haben.

https://neradni-dani.com/feiertage-kroatien.php

**Comment by fstueber** [comment]
Hallo. Danke für die Information. Der Feiertag ist eingefügt.
Thanks for the information. This public holiday has been added.
