### ISSUE TITLE
NL King’s Day in 2025 is day earlier

### ISSUE THREAD

**Issue by peteruithoven** [openpotato/openholidaysapi.data#52]
The public holidays data for Netherlands has the wrong date for King’s Day in 2025. 
```
31349587-ddaa-4fd0-9752-7fc786c25208;NL;2025-04-27;;Public;NL Koningsdag,DE Königstag,EN King’s Day
```

2025-04-27 happens to fall on a Sunday, which means it's celebrated a day earlier. 

https://en.wikipedia.org/wiki/Koningsdag#Changing_of_the_date
> if not on a Sunday. If that occurred, which was true for 2014 itself as well, King's Day will again be held on Saturdays preceding the 27th. 

https://publicholidays.nl/kings-day/
https://www.koninklijkhuis.nl/onderwerpen/koningsdag (only available in dutch)
https://www.amsterdam.nl/toerisme-vrije-tijd/evenementen/koningsdag-2025/
https://www.kalender-365.nl/feestdagen/koningsdag.html
https://www.iamexpat.nl/expat-info/dutch-holidays

On behalf of my country I'm sorry for these exceptions ;)

**Comment by peteruithoven** [comment]
Sadly the official source mentioned on the following page doesn't yet include 2025 data.
https://www.openholidaysapi.org/en/sources/#netherlands

**Comment by fstueber** [comment]
Thanks a lot for the feedback. King's Day for 2025 has been corrected. I have added also some info here: https://www.openholidaysapi.org/en/sources/#netherlands

**Comment by peteruithoven** [comment]
Thanks @fstueber !

Commit: https://github.com/openpotato/openholidaysapi.data/commit/276989e593b814e6f26da6a5c179bc3bc8167bbf!
