### ISSUE TITLE
Missing school holidays from season 2024/2025 in PL

### ISSUE THREAD

**Issue by pczyzyk** [openpotato/openholidaysapi.data#56]
There are missing holidays from PL from this document:
https://www.gov.pl/web/edukacja/kalendarz-roku-szkolnego-20242025

Only regional winter holidays are available:
https://www.gov.pl/web/edukacja/terminy-ferii-zimowych-w-roku-szkolnym-20252026

**Comment by fstueber** [comment]
Done. Please check.

**Comment by pczyzyk** [comment]
Perfect - everything is there. Thank you!
