### ISSUE TITLE
Error in public holidays for Lucerne, Switzerland since last update

### ISSUE THREAD

**Issue by s-broda** [openpotato/openholidaysapi.data#60]
I have noticed that as of today, Berchtoldstag (Jan 2nd), Ostermontag, and Pfingstmontag are no longer returned for the Swiss Canton of Lucerne when using `subdivisionCode=CH-LU` in the query. Is this intended? It appears to be a mistake - I work in Lucerne, and these are very much holidays. The full query I'm using is `https://openholidaysapi.org/PublicHolidays?countryIsoCode=CH&languageIsoCode=DE&validFrom=2024-01-01&validTo=2024-12-31&subdivisionCode=CH-LU`

Thanks for this wonderful project!
Cheers
Simon

**Comment by fstueber** [comment]
Hi. Thanks for the feedback. Berchtoldstag (Jan 2nd), Ostermontag, and Pfingstmontag are no legally recognised public holidays. See: https://srl.lu.ch/app/de/texts_of_law/855. It seems that the days are free of work anyway. I will re-introduce them with a special tag.

**Comment by s-broda** [comment]
Indeed per that document it seems that these are not legally recognized cantonal holidays, so every municipality (Gemeinde) may be able to decide for itself. I'd be surprised though if there were any that didn't designate them as a holiday.

On the other hand, I found [this official looking document](https://www.ejpd.admin.ch/dam/bj/de/data/publiservice/service/zivilprozessrecht/kant-feiertage.pdf.download.pdf/kant-feiertage.pdf) (direct pdf link) by the federal government that does list all 3 as holidays in the canton of Lucerne.

In any case, listing them (perhaps with a special tag as you say) will probably be least surprising to your users. My guess is that the same is true for most cantons. For example, as per [this website](https://www.ferienwiki.ch/feiertage/ostermontag), Easter Monday is a holiday everywhere except for Valais and parts of Aargau und Solothurn. For Pentacost, it seems that [Argau is the only exception](https://feiertag.info/info/feiertage/pfingstmontag-in-der-schweiz/). Berchtholdstag is different apparently in that it does seem to [differ across cantons](https://www.feiertagskalender.ch/feiertag.php?geo=3056&ft_id=3). Of course these are low quality sources, to the pdf above might be your best option as to a single source of truth.

Thanks again for a great tool!

**Comment by s-broda** [comment]
Thank you for getting around to it so quickly!
