### ISSUE TITLE
Zero results request for Spain in 2025

### ISSUE THREAD

**Issue by danielchicote** [openpotato/openholidaysapi.data#61]
Hello people, this query gives zero results:

https://openholidaysapi.org/PublicHolidays?countryIsoCode=ES&languageIsoCode=ES&validFrom=2025-01-01&validTo=2025-12-31

But this others  gives the correct results:
https://openholidaysapi.org/PublicHolidays?countryIsoCode=ES&languageIsoCode=ES&validFrom=2023-01-01&validTo=2024-12-31
https://openholidaysapi.org/SchoolHolidays?countryIsoCode=ES&languageIsoCode=ES&validFrom=2025-01-01&validTo=2025-12-31

Whats wrong? There is no holidays data for 2025?

**Comment by fstueber** [comment]
Public holidays for 2025 now added, please check
