### ISSUE TITLE
Incomplete holidays for Switzerland year 2025

### ISSUE THREAD

**Issue by danieldotnet** [openpotato/openholidaysapi.data#64]
For the year 2025 in the canton of Valais, the holidays are incomplete, only the winter holidays are visible.

Following the URL:
https://openholidaysapi.org/SchoolHolidays?countryIsoCode=CH&subdivisionCode=CH-VS&languageIsoCode=DE&validFrom=2025-01-01&validTo=2025-12-31

**Comment by fstueber** [comment]
2025 should be complete now
