### ISSUE TITLE
Wrong Holiday for CH-SG [Berchtoldstag]

### ISSUE THREAD

**Issue by KillTrot** [openpotato/openholidaysapi.data#67]
According to the data source listed for the Canton of St. Gallen in Switzerland, the Berchtoldstag (2nd of January) is not a public holiday:

[https://www.gesetzessammlung.sg.ch/app/de/texts_of_law/552.1](https://www.gesetzessammlung.sg.ch/app/de/texts_of_law/552.1)

**Comment by fstueber** [comment]
Hi, yes, that's true. But according to [Bundesamt für Justiz BJ](https://www.bj.admin.ch/dam/bj/de/data/publiservice/service/zivilprozessrecht/kant-feiertage.pdf.download.pdf/kant-feiertage.pdf) Berchtoldstag (2nd of January) is treated like a public holiday. Officially, it's a normal working day, but in practice most authorities and businesses are closed.

**Comment by KillTrot** [comment]
I get where you're coming from.
I guess in the end it's a question of the concept how we want to treat those holidays, that by law are not holidays but are treated as holidays.
Maybe a new property to indicate, that this holiday is not a "mandatory" holiday would be an option?
Or to use a different type for those?

**Comment by fstueber** [comment]
Actually, there is already a holiday type 'Optional' available, which can be used for that.
