### ISSUE TITLE
Saint-Pierre-et-Miquelon has incorrect ISO code

### ISSUE THREAD

**Issue by csirmazbendeguz** [openpotato/openholidaysapi.data#68]
The OpenHolidays API returns the ISO code `FR-975` (instead of `FR-PM`) for the _Saint-Pierre-et-Miquelon_ subdivision.

I did a quick search on Google but I couldn't find anything related to `FR-975`, I'm not sure where it came from?

**Comment by fstueber** [comment]
Fixed. Thanks for the pull request.

**Comment by fstueber** [comment]
Fixed. See #70
