### ISSUE TITLE
Information for the next Páscoa (Easter) for 2025 is totally wrong

### ISSUE THREAD

**Issue by fstueber** [openpotato/openholidaysapi.data#70]
Hello guys, I dont know what else to report this, but the information for the next Páscoa (Easter) for 2025 is totally wrong. 

```
openholidaysapi.org/PublicHolidays?countryIsoCode=PT&languageIsoCode=PT&validFrom=2025-01-01&validTo=2025-12-31](https://openholidaysapi.org/PublicHolidays?countryIsoCode=PT&languageIsoCode=PT&validFrom=2025-01-01&validTo=2025-12-31
```
It is showing 

```
{
    "id": "6dc9e537-28fc-43f1-b739-1c831c6e2f34",
    "startDate": "2025-04-07",
    "endDate": "2025-04-07",
    "type": "Public",
    "name": [
      {
        "language": "PT",
        "text": "Sexta-feira Santa"
      }
    ],
    "regionalScope": "National",
    "temporalScope": "FullDay",
    "nationwide": true
  }
```

  ```
{
    "id": "035df30c-4f45-4e47-9205-75e2b5dcf802",
    "startDate": "2025-04-09",
    "endDate": "2025-04-09",
    "type": "Public",
    "name": [
      {
        "language": "PT",
        "text": "Domingo de Páscoa"
      }
    ],
    "regionalScope": "National",
    "temporalScope": "FullDay",
    "nationwide": true
  }
```

the real dates are:

![Presentify 2024-11-12 18 03 34](https://github.com/user-attachments/assets/535bd11a-b0b7-4146-8f89-877d3832cdb1)

Can I support you on something?

_Originally posted by @igordevezas in https://github.com/openpotato/openholidaysapi.data/issues/21#issuecomment-2471226200_

**Comment by fstueber** [comment]
Fixed. Please check. Thank you for reporting @igordevezas. Any other mistakes in the Portugal dates?

**Comment by igordevezas** [comment]
Hello @fstueber, not that I could see (at least for 2025), thank you very much. 🎉

Question: are you fixing this manually? Is there a way to anticipate such things?

**Comment by fstueber** [comment]
Yes, this is fixed manually. You can find the raw for Portugal data here: https://github.com/openpotato/openholidaysapi.data/tree/develop/src/pt/holidays
