### ISSUE TITLE
404 Not Found errors for all urls?

### ISSUE THREAD

**Issue by toonvl** [openpotato/openholidaysapi.data#75]
I now get 404 errors for seemingly every call?

{"type":"https://tools.ietf.org/html/rfc9110#section-15.5.5","title":"Not Found","status":404,"traceId":"00-a57e3dee82dd9641d6129104c97e5cc8-1d3d03ac160055c6-00"}

https://openholidaysapi.org/Countries
https://openholidaysapi.org/Languages
https://openholidaysapi.org/Subdivisions?countryIsoCode=DE
...

Is something fundamental broken? Can you please check?

Kr,
Toon

**Comment by BeyondVertical** [comment]
I had the same problem. The URLs seem to have changed. Check the API and change the URLs. That is what I have done and it works again.

**Comment by fstueber** [comment]
The urls have changed, yes, but that was not planned and does not fit to documentation. Its simply a bug. Will fix this today.

**Comment by fstueber** [comment]
Fixed. Please check.

**Comment by BeyondVertical** [comment]
Yeah, working again with the old URLs. Thanks.

**Comment by toonvl** [comment]
Yes, working here as well. Thanks!
